package lexer.token;

public enum TokenType {
    INT, FLOAT, DOUBLE, CHAR, BOOL, STRING, ARRAY,
    PRINT, SCAN,
    ASSIGN,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT,
    LT, LE, GT, GE, EQ, NEQ,
    MAIN, RETURN,
    IF, ELSE, ELSE_IF, FOR, WHILE, DO,
    AND, OR,
    IDENT, INT_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON, LUGLASTA, RUGLASTA,
    NEWLINE, EOF,
    GRESKA
}
