package lexer.token;

public enum TokenType {
    INT, FLOAT, DOUBLE, CHAR, BOOL, STRING,
    PRINT, SCAN,
    ASSIGN,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, PERCENT, POW,
    LT, LE, GT, GE, EQ, NEQ,
    MAIN, RETURN,
    IF, ELSE, ELSE_IF, FOR, WHILE, DO,
    AND, OR,
    IDENT, INT_LIT, FlOAT_LIT, DOUBLE_LIT,
    LPAREN, RPAREN, LBRACKET, RBRACKET, SEPARATOR_COMMA, TYPE_COLON, LUGLASTA, RUGLASTA,
    NEWLINE, EOF,
    GRESKA,
    NULA, JEDAN, DVA, TRI, CETIRI, PET, SEST, SEDAM, OSAM, DEVET
}
